server:
  port:8080
disk:
  upload:
    basepath: C:/Users/2106731/uploads
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/plantshop?createDatabaseIfNotExist=true&useUnicode=true
    username: root
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
